import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import React from "react";
import Header from "@/app/_components/header";
import Footer from "@/app/_components/footer";
import {cn} from "@/lib/utils";

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-sans"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth h-full">
    <body className={cn(
      "min-h-screen bg-background font-sans antialiased flex flex-col",
      rubik.variable
    )}>
      <Header/>
        <main className="w-full grow">
          {children}
        </main>
      <Footer/>
    </body>
    </html>
);
}
